### PR TITLE
doors.lua update

### PR DESCRIPTION
**Pull request by EPuncker**
### Pull Request Prelude

- [x] I have followed [proper The Forgotten Server code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/otland/forgottenserver/wiki/Contributing
[code]: https://github.com/otland/forgottenserver/wiki/TFS-Coding-Style-Guide

### CODE REVIEW

**Comment by silic0nalph4** [comment]
It's definitely working better than my PR!

✅ Normal doors are ok - they can be opened and closed again.
image
image

✅ House doors are ok - they can be opened and closed again.
image
image

⛔ Quest doors aren't working (or there might be a bug in the Tutorial Island quest)
image
image

❓ Locked doors - not tested yet; I need to find a key!

**Comment by silic0nalph4** [comment]
⛔ Hmm... there are some doors that _should_ by openable which appear as locked. For example, at Lonely Sea Side Hotel in Carlin:

image

The door isn't openable, so you can't get to the house.

image

Another example is the door to the Carlin crypt. The main entrance is locked (I don't think it should be)
image

✅ The better news is that keys (or at least key 3520) are working!

image

image

image

**Comment by silic0nalph4** [comment]
I've also found some doors that _should_ be locked but aren't, e.g. Alawar's Vault in Senja.
image

**Comment by EPuncker** [comment]
@silic0nalph4 thanks, that means the script is working fine, the problem is only the map now, I'll review every door on it and fix them to the correct one (note: beginner content as: dawnport, rookgaard, etc. will not be touched as of now)

**Pull request merged**
